stages:
    - build

build_apk:
    stage: build
    image: gitlab.espressif.cn:5050/esp_rainmaker/cloud_backend/cloudbackend:22May26py313
    tags:
        - rmng

    variables:
      deployment: "production"  

    rules:
        - if: '$CI_MERGE_REQUEST_TITLE =~ /^\s*(WIP|Draft)/'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: always

    script:
        - git clone --single-branch --depth 1 https://$CI_GITLAB_USERNAME_APP_FRAMEWORKS:$CI_GITLAB_PASSWORD_APP_FRAMEWORKS@gitlab.espressif.cn:6688/app-frameworks/eagle.git
        - cd eagle/tools/gitci
        - pip3 install -r requirements.txt
        - python3 -u esp_rm_android_app.py --branch ${CI_COMMIT_REF_NAME} --deployment ${deployment}
